### ISSUE TITLE
mxgraph 的xml用官方的接口在vue中为什么直接回显不出来，方便交流一下么？

### ISSUE THREAD

**Issue by 0muxi0** [whenTheMorningDark/workinteresting#1]
代码如下，
const xml = decodeURIComponent(myData.xml)
var xmlDocument = MxUtils.parseXml(xml)
var decoder = new MxCodec(xmlDocument)
var node = xmlDocument.documentElement
decoder.decode(node, this.graph.getModel())

**Comment by whenTheMorningDark** [comment]
我之前也碰到过这个问题，我debugger进去发现少了mxGraphModel类，你需要在初始化的时候加上
window.mxGraphModel = MxGraphModel;
window.mxGeometry = MxGeometry;
 this.MxGraphModel = new MxGraphModel();
这样应该能解决你的问题，如果实在不行，可以参考我的json格式返回数据，让图形回显，

**Comment by 0muxi0** [comment]
试了好几下那两个对象都已经在window对象上仍旧无济于事。json格式我们后端不支持这样做，所以就不考虑了。    你说的debugger进去是指那几行代码都去看他们的值是否都正确？

**Comment by 0muxi0** [comment]
> 我之前也碰到过这个问题，我debugger进去发现少了mxGraphModel类，你需要在初始化的时候加上
> window.mxGraphModel = MxGraphModel;
> window.mxGeometry = MxGeometry;
> this.MxGraphModel = new MxGraphModel();
> 这样应该能解决你的问题，如果实在不行，可以参考我的json格式返回数据，让图形回显，

试了好几下那两个对象都已经在window对象上仍旧无济于事。json格式我们后端不支持这样做，所以就不考虑了。    你说的debugger进去是指那几行代码都去看他们的值是否都正确？

**Comment by whenTheMorningDark** [comment]
> > 我之前也碰到过这个问题，我debugger进去发现少了mxGraphModel类，你需要在初始化的时候加上
> > window.mxGraphModel = MxGraphModel;
> > window.mxGeometry = MxGeometry;
> > this.MxGraphModel = new MxGraphModel();
> > 这样应该能解决你的问题，如果实在不行，可以参考我的json格式返回数据，让图形回显，
> 
> 试了好几下那两个对象都已经在window对象上仍旧无济于事。json格式我们后端不支持这样做，所以就不考虑了。 你说的debugger进去是指那几行代码都去看他们的值是否都正确？

是的 我之前没有添加这两句话的时候 我debugger进去，发现mxGraphModel是undefine的，所以就不能回显....我等下上去看看我之前写的代码 然后再和你讨论一下

**Comment by whenTheMorningDark** [comment]
> > 我之前也碰到过这个问题，我debugger进去发现少了mxGraphModel类，你需要在初始化的时候加上
> > window.mxGraphModel = MxGraphModel;
> > window.mxGeometry = MxGeometry;
> > this.MxGraphModel = new MxGraphModel();
> > 这样应该能解决你的问题，如果实在不行，可以参考我的json格式返回数据，让图形回显，
> 
> 试了好几下那两个对象都已经在window对象上仍旧无济于事。json格式我们后端不支持这样做，所以就不考虑了。 你说的debugger进去是指那几行代码都去看他们的值是否都正确？

我这里没有问题呢，你还是不行的话 可以加我qq 404792402,我们可以讨论一下。
